// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ID             uuid.UUID
	Title          string
	UserEmail      string
	LastActiveDate time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Message struct {
	ID         uuid.UUID
	Content    string
	SenderType string
	ChatID     uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
